# Generated by Django 3.1.4 on 2020-12-27 11:19

from django.db import migrations, models
import django.db.models.deletion
import impreza.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(default=1)),
                ('max_age', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GeographicCords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('ns', 'ns'), ('we', 'we')], max_length=10)),
                ('degrees', models.IntegerField(default=1)),
                ('minutes', models.IntegerField(default=1)),
                ('seconds', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_provider', models.CharField(default='email', max_length=255)),
                ('description', models.CharField(max_length=3000)),
                ('age', models.IntegerField(default=1)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('avatar', models.ImageField(blank=True, upload_to=impreza.models.User.get_hashed)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_guest_created', to='impreza.cordinates')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField()),
                ('member_count', models.IntegerField(default=1)),
                ('max_member_count', models.IntegerField(default=1)),
                ('is_selction', models.BooleanField()),
                ('age_span', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='impreza.agespan')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('guests', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_guests_created', to='impreza.user')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_hosts_created', to='impreza.user')),
                ('local_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_local_created', to='impreza.cordinates')),
                ('room_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='impreza.roomstate')),
            ],
        ),
        migrations.AddField(
            model_name='cordinates',
            name='ns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cordinates_ns_created', to='impreza.geographiccords'),
        ),
        migrations.AddField(
            model_name='cordinates',
            name='we',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cordinates_we_created', to='impreza.geographiccords'),
        ),
    ]
