# Generated by Django 3.1.4 on 2020-12-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impreza', '0002_auto_20201204_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
