# Generated by Django 3.1.4 on 2020-12-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impreza', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
