# Generated by Django 3.1.4 on 2020-12-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impreza', '0005_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='image',
        ),
        migrations.AddField(
            model_name='guest',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_guest_created', to='impreza.cordinates'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
