# Generated by Django 3.1.4 on 2020-12-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impreza', '0006_auto_20201210_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
