# Generated by Django 3.1.4 on 2020-12-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impreza', '0007_auto_20201210_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
