# Generated by Django 3.1.4 on 2020-12-13 16:49

from django.db import migrations, models
import django.db.models.deletion
import impreza.models


class Migration(migrations.Migration):

    dependencies = [
        ('impreza', '0008_guest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(max_length=3000)),
                ('age', models.IntegerField(default=1)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('avatar', models.ImageField(blank=True, upload_to=impreza.models.User.get_hashed)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_guest_created', to='impreza.cordinates')),
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='guest_ptr',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.AddField(
            model_name='local',
            name='guests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_guests_created', to='impreza.user'),
        ),
        migrations.AddField(
            model_name='local',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_hosts_created', to='impreza.user'),
        ),
    ]
